name: computer_service_system
description: CSS Mobile Application v1_0606


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  flutter_swiper: ^1.1.6
  provider: ^6.0.3
  http: ^0.13.4
  intl: ^0.17.0
  syncfusion_flutter_datagrid: ^20.2.40
  modal_progress_hud_nsn: ^0.3.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.3
  awesome_dialog: ^2.2.1
  async: ^2.8.2
  loading_overlay: ^0.3.0
  image_picker: ^0.8.5+3
  dio: ^4.0.6
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  pin_code_fields: ^7.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/HoChiMinhCityDistricts.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launch_image.png"